apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-stable-hpa
  namespace: app-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-stable
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
