apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
reclaimPolicy: Delete
# This manifest defines a StorageClass for dynamic provisioning of AWS EBS gp3 volumes in Kubernetes.
# StorageClasses allow you to define how storage is provisioned and managed for PersistentVolumeClaims.

apiVersion: storage.k8s.io/v1        # Specifies the API version for the StorageClass resource.
kind: StorageClass                   # Declares the type of resource as StorageClass.
metadata:
  name: ebs-gp3                      # The name assigned to this StorageClass.
provisioner: ebs.csi.aws.com         # Specifies the CSI driver for AWS EBS volumes.
volumeBindingMode: WaitForFirstConsumer # Delays volume binding until a Pod using the PVC is scheduled.
allowVolumeExpansion: true           # Allows the volume to be resized after creation.
parameters:
  type: gp3                          # Sets the EBS volume type to gp3 (General Purpose SSD).
reclaimPolicy: Delete                # Deletes the underlying volume when the PVC is deleted.

# --- Kubernetes Keywords Explanation ---

# apiVersion: Specifies the version of the Kubernetes API for the resource.
# kind: The type of Kubernetes resource (StorageClass in this case).
# metadata: Data that uniquely identifies the resource, such as its name.
# name: The unique name for the resource within its namespace.
# provisioner: The CSI driver responsible for provisioning storage (here, AWS EBS).
# volumeBindingMode: Controls when volume binding and dynamic provisioning occur.
# allowVolumeExpansion: Enables resizing of persistent volumes.
# parameters: Key-value pairs for configuring the storage backend.
# reclaimPolicy: Determines what happens to the physical storage when the PVC is deleted.

# --- AWS Keywords Explanation ---

# ebs.csi.aws.com: The Container Storage Interface (CSI) driver for AWS Elastic Block Store.
# type: gp3: Specifies the AWS EBS volume type as gp3 (General Purpose SSD).