apiVersion: v1
kind: Pod
metadata:
  name: testpod-b
  namespace: netlab
  labels: { app: b }
spec:
  containers:
  - name: web
    image: hashicorp/http-echo:1.0.0
    args: ["-listen=:8080","-text=hello-from-B"]
    ports:
    - containerPort: 8080
