apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: netlab
spec:
  replicas: 2
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello:plain-text
        ports:
        - name: http
          containerPort: 80
